"""Added MyntraUser and Product models

Revision ID: b43ecd446575
Revises: e867f21e252a
Create Date: 2024-07-14 21:31:43.402065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43ecd446575'
down_revision = 'e867f21e252a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('myntraid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.drop_column('myntraid')

    # ### end Alembic commands ###
