"""Add myntra column to Pin model

Revision ID: de86519c9d5e
Revises: a382d003f4d5
Create Date: 2024-07-13 15:32:31.176048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de86519c9d5e'
down_revision = 'a382d003f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('myntra', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.drop_column('myntra')

    # ### end Alembic commands ###
