"""Added MyntraUser2 and Product models

Revision ID: e867f21e252a
Revises: ba48547361df
Create Date: 2024-07-13 19:24:24.323372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e867f21e252a'
down_revision = 'ba48547361df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###
