"""Added MyntraUser2 and Product models

Revision ID: f0e538f2c19d
Revises: a44c30d09fab
Create Date: 2024-07-13 18:58:42.316214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e538f2c19d'
down_revision = 'a44c30d09fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
